spin_manifest_version = 2

[application]
name = "advent-of-spin-challenge-one"
version = "0.1.0"
authors = ["James Hagans <jhagans@acm.org>"]
description = "advent of spin week 1 challenge"

[[trigger.http]]
route = "/index.html"
component = "fs"

[[trigger.http]]
route = "/data"
component = "advent-of-spin-challenge-one"

[component.fs]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "", destination = "/index.html" }]


[component.advent-of-spin-challenge-one]
source = "target/wasm32-wasi/release/advent_of_spin_challenge_one.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.advent-of-spin-challenge-one.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]


